#include <iostream>
#include <vector>
#include <string>
#include <typeinfo>
#include <utility>
#pragma warning(push)
#pragma warning(disable:4800)
#include "mpir.h"
#include "mpirxx.h"
#pragma warning(pop)
